services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: runnerz
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data
